### PR TITLE
Back up and restore Postgres data when container stops

### LINKED ISSUE #8: Back up Postgres data when container stops
As of PR #6, any data created in geocml_db while the container was running is deleted when the container stops. We should ensure that when a geoCML container stops that the Postgres database within the container is backed up to a permanent storage location. Further, when a container is started we should check for any backups that maybe present on the host device and restore the geocml_db database once the container goes back up.

### PR DESCRIPTION
**Pull request by TristanDamron**
Resolves #8

This PR implements the geoCML Task Scheduler (gTS) framework; this will allow us to easily schedule async Python functions to automate tasks inside the container. This PR implements two tasks: backup_geocml_db and restore_geocml_db_from_backups. backup_geocml_db is responsible for creating SQL dumps for each table in geocml_db. This task runs every hour and saves the backed up SQL files to /home/kasm-user/DBBackups. restore_geocml_db_from_backups is responsible for restoring tables from backed up SQL files inside the most recent backup directory. This task runs every second until a backup is restored, then it is stopped. If there are no recent backups then the task just stops, releasing a thread for another task in the schedule. The task scheduler logs can be found under /home/kasm-user/Logs. 

The backup_geocml_db / restore_geocml_db_from_backups tasks will ensure that users will not lose their data if the container goes down for whatever reason.

### CODE REVIEW

**Comment by TristanDamron** [comment]
@capsulecorplab This PR is ready for you to review! As far as testing, there are a couple of things you should keep in mind...

- The geoCML Task Scheduler (gTS) can be found at `/home/kasm-user/Utils/geocml-task-scheduler`. There, you'll find the source code for both of the tasks I've implemented with this PR (backup_geocml_db and restore_geocml_db_from_backups) as well as source code for the Tasks superclass, the task schedule, and task logging.

- By default, backup_geocml_db is scheduled to run once every hour. restore_geocml_db_from_backups, on the other hand, is scheduled to run every second until it either a) restores geocml_db tables from the most recent back up or b) it determines that there are no backups to restore from. You can change the frequency of these tasks (or disable them entirely) by editing schedule.py in the gTS directory.

- The backup_geocml_db task does not do a complete backup of the database. Rather, it backs up all database tables and schema (schema as-in PostgreSQL namespaces). This method seems sufficient for this PR, but keep in mind that we may need to come back to this at a later date; I can see potential issues with coded value domains, for example. Hopefully testing this PR will bring to light what issues exist so we can handle them in a future PR.

- backup_geocml_db creates a timestamped directory containing your backed up tables. You can find your backups at `/home/kasm-user/DBBackups`

- As gTS runs tasks, it populates a log file called task_log. You can find this log file at `/home/kasm-user/Logs/task_log`. For testing, it will probably be helpful to tail task_log and watch for any errors. 

Here's a step-by-step testing workflow that should help you validate that everything is working correctly:
1. Build and run the container
2. Start the postgresql service
3. Open QGIS and connect to geocml_db
4. Add a few shapefile layers to the database's public schema (points, polylines, polygons, whatever you'd like! I strongly recommend adding a variety of custom fields to these data, each with different datatypes).
5. Create one or more new schema (again, schema as in PostgreSQL namespace) in geocml_db and add some more shapefile layers with custom fields.
6. Digitize some features into the layers you created (maybe make a map of rivers and towns in Montana?)
7. MAKE SURE THAT backup_geocml_db RAN AND THAT THERE IS SOMETHING IN DBBackups.
8. Bring down the container.
9. Bring it back up.
10. Restart the postgresql service.
11. Tail the task_log; assert that a message appears telling you that the task restored geocml_db with the tables you created.
12. Open QGIS, connect to geocml_db.
13. Assert that the layers you made still exist in the database and that all of the digitized features you created are present.

**Comment by capsulecorplab** [comment]
Got following traceback error while attempting to backup geocml database
```
>>> import backup_geocml_db
>>> backup_geocml_db.backup_geocml_db()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kasm-user/Utils/geocml-task-scheduler/backup_geocml_db.py", line 73, in backup_geocml_db
    path_to_backup_dir.rmdir()
  File "/usr/lib/python3.8/pathlib.py", line 1336, in rmdir
    self._accessor.rmdir(self)
OSError: [Errno 39] Directory not empty: '/home/kasm-user/DBBackups/1661404799.1842601'
```

**Comment by TristanDamron** [comment]
@capsulecorplab Fixed that with 0c03d34! 

I found another bug related to handling escape sequences, but I'll have to get that fix to you tomorrow/Monday.

**Comment by TristanDamron** [comment]
@capsulecorplab I found a much better way to copy and restore PostgreSQL data with Python! [9f25cfb](https://github.com/geoCML/geocml-base-image/pull/18/commits/9f25cfbda2969ad2a0dbc3fe2b467ee17fbcdb84) makes a couple of changes that you should take note of. In the DBBackup directory, you'll now find two types of back up files: schema and data. The schema files are SQL files that are used to rebuild the table and schema, where as the data files are CSV files that can be used to insert  rows of data into the table created by the schema file. For each database table, there will be one schema and data file each.

We're still not doing a good enough job of backing up coded value domains and other custom data types. I'm tempted to make that a separate issue for the next release, but I'd like to get your thoughts first.

**Comment by TristanDamron** [comment]
@capsulecorplab Is this ready to be merged?

**Comment by capsulecorplab** [comment]
Apologies for lagging on this PR! I got the image built and running but am running into credential issues trying to connect to geocml_db
Screenshot from 2022-09-13 22-08-50

**Comment by TristanDamron** [comment]
@capsulecorplab It looks like you're db connection settings are trying to connect to a database called 'geocml' not 'geocml_db'. I would double check your connection settings and see if that fixes it!

**Comment by capsulecorplab** [comment]
`geocml` is the user name/password, but the connection name I'm trying to create is `geocml_db`. I'm not sure what I'm doing wrong 
Screenshot from 2022-09-15 14-26-32

**Comment by TristanDamron** [comment]
@capsulecorplab Ahh I see the problem. In the 'Create a new PostGIS Connection' window, 'Name' doesn't refer to the name of the database. 'Name' is just a friendly name for the connection. Try adding 'geocml_db' to the 'Database' field!

**Comment by capsulecorplab** [comment]
> @capsulecorplab Ahh I see the problem. In the 'Create a new PostGIS Connection' window, 'Name' doesn't refer to the name of the database. 'Name' is just a friendly name for the connection. Try adding 'geocml_db' to the 'Database' field!

Ah, that makes sense :facepalm:

**Pull request merged**
